#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 18 13:30:53 2020

@author: Emeline
"""
import sys
sys.path.insert(0,"/Users/Emeline/Documents/NASA_Internship_2020/Github/exoplots/scripts/")

import numpy as np
from bokeh import plotting
from bokeh.embed import components
from bokeh.io import curdoc
from bokeh.models import FuncTickFormatter, OpenURL, TapTool
from bokeh.models import Label, Legend, LegendItem, LogAxis, Range1d
from bokeh.themes import Theme

from utils import get_update_time, load_data, log_axis_labels

# get the exoplot theme
theme = Theme(filename="./exoplots_theme.yaml")
curdoc().theme = theme

# what order to plot things and what the legend labels will say
missions = ['Kepler Candidate', 'Kepler Confirmed', 'K2 Candidate',
            'K2 Confirmed', 'TESS Candidate', 'Other Confirmed',
            'TESS Confirmed']

#legend for temperatures
temps = ['F Confirmed','F Candidate', 'G Confirmed', 'G Candidate', 'K Confirmed','K Candidate', 'M Confirmed','M Candidate']

# markers and colors in the same order as the missions above
markers = ['circle_cross', 'circle', 'square_cross', 'square',
           'inverted_triangle', 'triangle', 'hex', 'hex_dot']
# colorblind friendly palette from https://personal.sron.nl/~pault/
# other ideas:
# https://thenode.biologists.com/data-visualization-with-flying-colors/research/
colors = ['#228833', '#228833', '#ee6677', '#ee6677', '#ccbb44', '#ccbb44', '#005cff', '#005cff']

# load the data
dfcon, dfkoi, dfk2, dftoi = load_data(updated_koi_params=True,
                                      updated_k2_params=True)

# what to display when hovering over a data point
TOOLTIPS = [
    ("Planet", "@planet"),
    # only give the decimal and sig figs if needed
    ("Insolation", "@insolation{0,0[.][00]} Earths"),
    ("Radius", "@radius{0,0[.][00]} Earth; @jupradius{0,0[.][0000]} Jup"),
    ("Period", "@period{0,0[.][0000]} days"),
    ("Star Temperature", "@temperature{0,0[.][00]} Kelvin"),
    ("Discovered by", "@discovery"),
    ("Status", "@status")
]

for ifig in np.arange(2):

    # output files
    if ifig == 0:
        embedfile = '_includes/insol_rad_toggletemp_embed.html'
        fullfile = '_includes/insol_rad_toggletemp.html'
    else:
        embedfile = '_includes/radius_gap_toggletemp_embed.html'
        fullfile = '_includes/radius_gap_toggletemp.html'

    # set up the full output file
    plotting.output_file(fullfile, title='Insolation Radius Plot')

    # create the figure
    if ifig == 0:
        fig = plotting.figure(x_axis_type='log', y_axis_type='log',
                              tooltips=TOOLTIPS, plot_height=700)
    else:
        fig = plotting.figure(x_axis_type='log', y_axis_type='linear',
                              tooltips=TOOLTIPS, plot_height=700)
    # allow for something to happen when you click on data points
    fig.add_tools(TapTool())

    # need to store min and max radius values to create the second axis
    ymin = 1
    ymax = 1

    # save the output plots to rearrange them in the legend
    glyphs = []
    counts = []

    for ii, imiss in enumerate(temps):
        # candidates get these default values
        alpha = 0.35
        size = 4
        # select the appropriate set of planets for each stellar type
        # make the confirmed planets more opaque and bigger
       #F hosts
        if imiss == 'F Confirmed':
            good =   (np.isfinite(dfcon['insol']) &
                     np.isfinite(dfcon['pl_rade']) &
                     np.isfinite(dfcon['st_teff']) &
                     (6000 <= dfcon['st_teff']) &
                     (7220 >= dfcon['st_teff']) &
                     np.isfinite(dfcon['pl_orbper']))
            alpha = 0.7
            size = 6
            print(imiss, ': ', good.sum())
        
        elif imiss == 'F Candidate':
            fac = imiss.split()[0]
            goodkoi = ((dfkoi['koi_disposition'] == 'Candidate') &
                    np.isfinite(dfkoi['insol']) &
                    np.isfinite(dfkoi['koi_prad']) &
                    np.isfinite(dfkoi['koi_steff']) &
                    (6000 <= dfkoi['koi_steff']) &
                    (7220 >= dfkoi['koi_steff']) &
                    dfcon['pl_tranflag'].astype(bool))
            goodtoi = ((dftoi['disp'] == 'Candidate') &
                    np.isfinite(dftoi['prade']) &
                    np.isfinite(dftoi['insol']) &
                    (6000 <= dftoi['Stellar Eff Temp (K)']) &
                    (7220 >= dftoi['Stellar Eff Temp (K)']))
            goodk2 = ((dfk2['k2c_disp'] == 'Candidate') &
                    np.isfinite(dfk2['pl_rade']) &
                    np.isfinite(dfk2['insol']) &
                    (6000 <= dfk2['st_teff']) &
                    (7220 >= dfk2['st_teff']) &
                    dfk2['k2c_recentflag'].astype(bool))
            alpha = 0.35
            size = 4
            print(imiss, ': ', good.sum())
            
        #G hosts
        elif imiss == 'G Confirmed':
            fac = imiss.split()[0]
            good =  (np.isfinite(dfcon['insol']) &
                    np.isfinite(dfcon['pl_rade']) &
                    np.isfinite(dfcon['st_teff']) &
                    (5340 <= dfcon['st_teff']) &
                    (5920 >= dfcon['st_teff']) &
                np.isfinite(dfcon['pl_orbper']))
            alpha = 0.7
            size = 6
            print(imiss, ': ', good.sum())
        
        elif imiss == 'G Candidate':
            fac = imiss.split()[0]
            goodkoi = ((dfkoi['koi_disposition'] == 'Candidate') &
                    np.isfinite(dfkoi['insol']) &
                    np.isfinite(dfkoi['koi_prad']) &
                    np.isfinite(dfkoi['koi_steff']) &
                    (5340 <= dfkoi['koi_steff']) &
                    (5920 >= dfkoi['koi_steff']) &
                    dfcon['pl_tranflag'].astype(bool))
            goodtoi = ((dftoi['disp'] == 'Candidate') &
                    np.isfinite(dftoi['prade']) &
                    np.isfinite(dftoi['insol']) &
                    (5340 <= dftoi['Stellar Eff Temp (K)']) &
                    (5920 >= dftoi['Stellar Eff Temp (K)']))
            goodk2 = ((dfk2['k2c_disp'] == 'Candidate') &
                    np.isfinite(dfk2['pl_rade']) &
                    np.isfinite(dfk2['insol']) &
                    (5340 <= dfk2['st_teff']) &
                    (5920 >= dfk2['st_teff']) &
                    dfk2['k2c_recentflag'].astype(bool))
            alpha = 0.35
            size = 4
            print(imiss, ': ', good.sum())
            
        #K hosts
        elif imiss == 'K Confirmed':
            fac = imiss.split()[0]
            good =  (np.isfinite(dfcon['insol']) &
                    np.isfinite(dfcon['pl_rade']) &
                    np.isfinite(dfcon['st_teff']) &
                    (3940 <= dfcon['st_teff']) &
                    (5280 >= dfcon['st_teff']) &
                    np.isfinite(dfcon['pl_orbper']))
            alpha = 0.7
            size = 6
            print(imiss, ': ', good.sum())
        
        elif imiss == 'K Candidate':
            fac = imiss.split()[0]
            goodkoi = ((dfkoi['koi_disposition'] == 'Candidate') &
                    np.isfinite(dfkoi['insol']) &
                    np.isfinite(dfkoi['koi_prad']) &
                    np.isfinite(dfkoi['koi_steff']) &
                    (3940 <= dfkoi['koi_steff']) &
                    (5280 >= dfkoi['koi_steff']) &
                    dfcon['pl_tranflag'].astype(bool))
            goodtoi = ((dftoi['disp'] == 'Candidate') &
                    np.isfinite(dftoi['prade']) &
                    np.isfinite(dftoi['insol']) &
                    (3940 <= dftoi['Stellar Eff Temp (K)']) &
                    (5280 >= dftoi['Stellar Eff Temp (K)']))
            goodk2 = ((dfk2['k2c_disp'] == 'Candidate') &
                    np.isfinite(dfk2['pl_rade']) &
                    np.isfinite(dfk2['insol']) &
                    (3940 <= dfk2['st_teff']) &
                    (5280 >= dfk2['st_teff']) &
                    dfk2['k2c_recentflag'].astype(bool))
            alpha = 0.35
            size = 4
            print(imiss, ': ', good.sum())
            
            
        #M hosts
        elif imiss == 'M Confirmed':
            fac = imiss.split()[0]
            good =  (np.isfinite(dfcon['insol']) &
                    np.isfinite(dfcon['pl_rade']) &
                    np.isfinite(dfcon['st_teff']) &
                    (2320 <= dfcon['st_teff']) &
                    (3870 >= dfcon['st_teff']) &
                    np.isfinite(dfcon['pl_orbper']))
            alpha = 0.7
            size = 6
            print(imiss, ': ', good.sum())
        
        elif imiss == 'M Candidate':
            fac = imiss.split()[0]
            goodkoi = ((dfkoi['koi_disposition'] == 'Candidate') &
                    np.isfinite(dfkoi['insol']) &
                    np.isfinite(dfkoi['koi_prad']) &
                    np.isfinite(dfkoi['koi_steff']) &
                    (2320 <= dfkoi['koi_steff']) &
                    (3870 >= dfkoi['koi_steff']) &
                    dfcon['pl_tranflag'].astype(bool))
            goodtoi = ((dftoi['disp'] == 'Candidate') &
                    np.isfinite(dftoi['prade']) &
                    np.isfinite(dftoi['insol']) &
                    (2320 <= dftoi['Stellar Eff Temp (K)']) &
                    (3870 >= dftoi['Stellar Eff Temp (K)']))
            goodk2 = ((dfk2['k2c_disp'] == 'Candidate') &
                    np.isfinite(dfk2['pl_rade']) &
                    np.isfinite(dfk2['insol']) &
                    (2320 <= dfk2['st_teff']) &
                    (3870 >= dfk2['st_teff']) &
                    dfk2['k2c_recentflag'].astype(bool))
            alpha = 0.35
            size = 4
            print(imiss, ': ', good.sum())
           
            
       #Sources    
        if 'Confirmed' in imiss:
            source = plotting.ColumnDataSource(data=dict(
                planet=dfcon['pl_name'][good],
                period=dfcon['pl_orbper'][good],
                host=dfcon['pl_hostname'][good],
                discovery=dfcon['pl_facility'][good],
                jupradius=dfcon['pl_radj'][good],
                radius=dfcon['pl_rade'][good],
                insolation=dfcon['insol'][good],
                temperature=dfcon['st_teff'][good],
                status=dfcon['status'][good],
                url=dfcon['url'][good]
                ))
            print(imiss, ': ', good.sum())
        
        elif 'Candidate' in imiss:
            source = plotting.ColumnDataSource(data=dict(
                planet=np.concatenate((dfkoi['kepoi_name'][goodkoi], dfk2['pl_name'][goodk2], dftoi['Planet Name'][goodtoi])),
                insolation=np.concatenate((dfkoi['insol'][goodkoi], dfk2['insol'][goodk2], dftoi['insol'][goodtoi])),
                period=np.concatenate((dfkoi['koi_period'][goodkoi], dfk2['pl_orbper'][goodk2], dftoi['period'][goodtoi])),
                radius=np.concatenate((dfkoi['koi_prad'][goodkoi], dfk2['pl_rade'][goodk2], dftoi['prade'][goodtoi])),
                temperature=np.concatenate((dfkoi['koi_steff'][goodkoi], dfk2['st_teff'][goodk2], dftoi['Stellar Eff Temp (K)'][goodtoi])),
                jupradius=np.concatenate((dfkoi['koi_pradj'][goodkoi], dfk2['pl_radj'][goodk2], dftoi['pradj'][goodtoi])),
                host=np.concatenate((dfkoi['kepid'][goodkoi], dfk2['epic_name'][goodk2], dftoi['host'][goodtoi])),
                discovery=np.concatenate((dfkoi['pl_facility'][goodkoi], dfk2['pl_facility'][goodk2], dftoi['pl_facility'][goodtoi])),
                status=np.concatenate((dfkoi['koi_disposition'][goodkoi], dfk2['k2c_disp'][goodk2], dftoi['disp'][goodtoi])),
                url=np.concatenate((dfkoi['url'][goodkoi], dfk2['url'][goodk2], dftoi['url'][goodtoi]))
                ))
            print(imiss, ': ', good.sum())
        
        counts.append(f'{good.sum():,}')

        

        # plot the planets
        # nonselection stuff is needed to prevent planets in that category from
        # disappearing when you click on a data point ("select" it)
        glyph = fig.scatter('insolation', 'radius', color=colors[ii],
                            source=source, size=size, alpha=alpha,
                            marker=markers[ii], nonselection_alpha=alpha,
                            nonselection_color=colors[ii])
        glyphs.append(glyph)
        # save the global min/max
        ymin = min(ymin, source.data['radius'].min())
        ymax = max(ymax, source.data['radius'].max())

    # set up where to send people when they click on a planet
    url = "@url"
    taptool = fig.select(TapTool)
    taptool.callback = OpenURL(url=url)

    # figure out what the default axis limits are
    if ifig == 0:
        ydiff = np.log10(ymax) - np.log10(ymin)
        ystart = 10.**(np.log10(ymin) - 0.05*ydiff)
        yend = 10.**(np.log10(ymax) + 0.05*ydiff)
    else:
        ystart = 0
        yend = 3.6

    # jupiter/earth radius ratio
    radratio = 11.21

    # set up the second axis with the proper scaling
    if ifig == 0:
        fig.extra_y_ranges = {"jup": Range1d(start=ystart/radratio,
                                             end=yend/radratio)}
        fig.add_layout(LogAxis(y_range_name="jup"), 'right')
    else:
        fig.y_range.start = ystart
        fig.y_range.end = yend
        fig.x_range.start = 40000
        fig.x_range.end = 0.1

    # add the first y-axis's label and use our custom log formatting
    fig.yaxis.axis_label = 'Radius (Earth Radii)'
    if ifig == 0:
        fig.yaxis.formatter = FuncTickFormatter(code=log_axis_labels())

    # add the x-axis's label and use our custom log formatting
    fig.xaxis.axis_label = 'Insolation (Earths)'
    fig.xaxis.formatter = FuncTickFormatter(code=log_axis_labels())
    # make high insolations on the left
    fig.x_range.flipped = True

    # add the second y-axis's label
    if ifig == 0:
        fig.right[0].axis_label = 'Radius (Jupiter Radii)'


    # which order to place the legend labels
    topleg = ['F Confirmed', 'F Candidate']
    middleleg = ['G Confirmed', 'G Candidate']
    bottomleg = ['K Confirmed', 'K Candidate']
    vbottomleg = ['M Confirmed', 'M Candidate']

    # set up all the legend objects
    items1 = [LegendItem(label=ii + f' ({counts[temps.index(ii)]})',
                         renderers=[glyphs[temps.index(ii)]])
              for ii in topleg]
    items2 = [LegendItem(label=ii + f' ({counts[temps.index(ii)]})',
                         renderers=[glyphs[temps.index(ii)]])
              for ii in middleleg]
    items3 = [LegendItem(label=ii + f' ({counts[temps.index(ii)]})',
                         renderers=[glyphs[temps.index(ii)]])
              for ii in bottomleg]
    items4 = [LegendItem(label=ii + f' ({counts[temps.index(ii)]})',
                         renderers=[glyphs[temps.index(ii)]])
              for ii in vbottomleg]

    # create the two legends
    for ii in np.arange(4):
        if ii == 0:
            items = items4
        elif ii == 1:
            items = items3
        elif ii == 2:
            items = items2
        else:
            items = items1
        legend = Legend(items=items, location="center")

        if ii == 3:
            legend.title = 'Discovered by and Status'
            legend.spacing = 10
        else:
            legend.spacing = 11

        if ifig == 0:
            legend.location = (-70, 5)
        else:
            legend.location = (-50, 5)
        legend.label_text_align = 'left'
        legend.margin = 0

        fig.add_layout(legend, 'above')    


    # overall figure title
    fig.title.text = 'Transiting Planets'

    # create the four lines of credit text in the two bottom corners
    if ifig == 0:
        label_opts1 = dict(
            x=-85, y=42,
            x_units='screen', y_units='screen'
        )

        label_opts2 = dict(
            x=-85, y=47,
            x_units='screen', y_units='screen'
        )

        label_opts3 = dict(
            x=612, y=79,
            x_units='screen', y_units='screen', text_align='right',
            text_font_size='9pt'
        )

        label_opts4 = dict(
            x=612, y=83,
            x_units='screen', y_units='screen', text_align='right',
            text_font_size='9pt'
        )
    else:
        label_opts1 = dict(
            x=-65, y=42,
            x_units='screen', y_units='screen'
        )

        label_opts2 = dict(
            x=-65, y=47,
            x_units='screen', y_units='screen'
        )

        label_opts3 = dict(
            x=632, y=79,
            x_units='screen', y_units='screen', text_align='right',
            text_font_size='9pt'
        )

        label_opts4 = dict(
            x=632, y=83,
            x_units='screen', y_units='screen', text_align='right',
            text_font_size='9pt'
        )

    msg1 = 'By Exoplots'
    # when did the data last get updated
    modtimestr = get_update_time().strftime('%Y %b %d')
    msg3 = 'Data: NASA Exoplanet Archive'
    msg4 = 'and ExoFOP-TESS'

    caption1 = Label(text=msg1, **label_opts1)
    caption2 = Label(text=modtimestr, **label_opts2)
    caption3 = Label(text=msg3, **label_opts3)
    caption4 = Label(text=msg4, **label_opts4)

    fig.add_layout(caption1, 'below')
    fig.add_layout(caption2, 'below')
    fig.add_layout(caption3, 'below')
    fig.add_layout(caption4, 'below')

    plotting.save(fig)

    # save the individual pieces so we can just embed the figure without the
    # whole html page
    script, div = components(fig, theme=theme)
    with open(embedfile, 'w') as ff:
        ff.write(script)
        ff.write(div)
